### ISSUE TITLE
Doesn't work in HA Docker container (HA Yellow)

### ISSUE THREAD

**Issue by scottjl** [hbrennhaeuser/homeassistant_integration_ntfy#1]
Just a FYI for anyone running HA in a Docker container, including on HA Yellow. This doesn't run because Python requests isn't installed.

`Platform error notify.ntfy - Requirements for ntfy not found: ['requests==2.25.1'].`

Not sure if there's a fix for this.

**Comment by hbrennhaeuser** [comment]
Thanks for the info.
I'm successfully running the integration on Home Assistant Operating System, which is running HA in Docker containers. 
According to the [docs](https://developers.home-assistant.io/docs/creating_integration_manifest#requirements), HA should automatically try to install all specified requirements. The problem therefore probably has another cause and should not be related to HA running containerized.

Could you try changing the requirements in your mainfest.json to `"requirements": ["requests"],`?
For some reason in I omitted the version specification in my running environment.

**Comment by scottjl** [comment]
That seems to have fixed it, I had to reboot the Yellow but it's passing a config check now without any issues. I haven't tried to send a notification yet, will later today when I have more time.

**Comment by hbrennhaeuser** [comment]
I removed the version specification https://github.com/hbrennhaeuser/homeassistant_integration_ntfy/commit/844e5ee2e06e8fdf45f8248f75da3d6652c6afdc .
