### ISSUE TITLE
Feature: Add support for file attachements

### ISSUE THREAD

**Issue by alexg-k** [hbrennhaeuser/homeassistant_integration_ntfy#7]
Thanks for this great plugin. I already make lots of use of it.

Now I would like to get notifications via ntfy.sh with an image of my surveillance camera attached if a certain state is reached. Well, I imagine something like this:
```diff
service: notify.ntfy_clients
data:
  title: Homeassistant Notification
- message: test123
+ local_file: /media/local/cam0_latest_detection.jpg
  data:
    tags: alarm
    priority: max
```

I am not proficient enough with python to do the pull request myself, sorry. [Documentation from ntfy.sh](https://docs.ntfy.sh/publish/#__tabbed_24_7)

EDIT: From what I understand from the documentation, sending an image requires a seperate http request (PUT) that cannot be combined with a message text. The http request in python for the example above should look similar to this:
```python
requests.put("https://ntfy.sh/homeassistant",
    data=open("/media/local/cam0_latest_detection.jpg", 'rb'),
    headers={"Filename": "cam0_latest_detection.jpg",
              "Title": "Homeassistant Notification",
              "Tags": "alarm",
              "Priority": "max"
    }
)
```

**Comment by hbrennhaeuser** [comment]
Thanks for the issue, I’m happy to hear the integration has proven useful to you.
I will definitely look into implementing support for sending attachments. 

Since I haven't tried this ntfy feature myself yet and I am busy the next days, it will probably be a short while before I can update this issue.

I’ll test how sending attachments works exactly and how to best implement this into this integration.

**Comment by hbrennhaeuser** [comment]
I have added support for attachments and released my changes as a new version `v1.1.0-pre.1`.
I have also added support for image-resizing and image-jpeg-compression which might be useful if you are using a high-resolution surveillance camera. 
Can you please check if the new features works for your intended use and check if you notice any problems?

**Comment by alexg-k** [comment]
Nice, thank you! This fully covers my needs.

**Comment by ptitbasou** [comment]
Thank you for your job. I install 1.1.0-pre2 because i need attachments too and it's ok.
